pipeline {
    agent any

    environment {
        PATH = "/usr/local/bin:$PATH"
    }
    tools {
        maven 'Maven'  // This must match the name you set in Global Tool Config
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/saif78692/order-service.git'
            }
        }
        stage('Build') {
            steps {
                dir('Order-Service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Test') {
            steps {
                dir('Order-Service') {
                    sh 'mvn test'
                }
            }
        }
        stage('Docker Build & Push') {
           steps {
               dir('Order-Service') {
                   withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                       sh '''
                           echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                           docker build -t saifsh78692/order-service:1.0 .
                           docker push saifsh78692/order-service:1.0
                       '''
                   }
               }
           }
        }
        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-credentials']) {
                    sh '''
                        ssh ec2-user@3.80.195.203 '
                        docker pull saifsh78692/order-service:1.0 &&
                        docker stop order || true &&
                        docker rm order || true &&
                        docker run -d -p 8080:8080 --name order saifsh78692/order-service:1.0
                        '
                    '''
                }
            }
        }
    }
}
